In [1]:
# ==========================================
# Basic tensor arithmetic by TensorFlow
# ==========================================

In [2]:
import tensorflow as tf
import numpy as np

In [3]:
print("TensorFlow Version " + tf.__version__)

TensorFlow Version 2.4.1


In [4]:
# Creating a tensor from a list
a = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
tensor_a = tf.convert_to_tensor(a)
print(tensor_a)

b = [[9, 8, 7], [6, 5, 4], [3, 2, 1]]
tensor_b = tf.convert_to_tensor(b)
print(tensor_b)

tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[9 8 7]
 [6 5 4]
 [3 2 1]], shape=(3, 3), dtype=int32)


In [5]:
# Creating a tensor from a NumPy array
np_a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=np.float32) 
np_tensor_a = tf.convert_to_tensor(np_a)
print(np_tensor_a)

np_b = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]], dtype=np.float32) 
np_tensor_b = tf.convert_to_tensor(np_b)
print(np_tensor_b)

tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[9. 8. 7.]
 [6. 5. 4.]
 [3. 2. 1.]], shape=(3, 3), dtype=float32)


In [6]:
# Creating a constant tensor
const_tensor_a = tf.constant([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=tf.float32)
print(const_tensor_a)

const_tensor_b = tf.constant([[9, 8, 7], [6, 5, 4], [3, 2, 1]], dtype=tf.float32)
print(const_tensor_b)

tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[9. 8. 7.]
 [6. 5. 4.]
 [3. 2. 1.]], shape=(3, 3), dtype=float32)


In [7]:
# Addition by element
add_tensor = tf.add(const_tensor_a, const_tensor_b)
print(add_tensor)

tf.Tensor(
[[10. 10. 10.]
 [10. 10. 10.]
 [10. 10. 10.]], shape=(3, 3), dtype=float32)


In [8]:
# Subtraction by element
subtract_tensor = tf.subtract(const_tensor_a, const_tensor_b)
print(subtract_tensor)

tf.Tensor(
[[-8. -6. -4.]
 [-2.  0.  2.]
 [ 4.  6.  8.]], shape=(3, 3), dtype=float32)


In [9]:
# Multiplication by element
multiply_tensor = tf.multiply(const_tensor_a, const_tensor_b)
print(multiply_tensor)

tf.Tensor(
[[ 9. 16. 21.]
 [24. 25. 24.]
 [21. 16.  9.]], shape=(3, 3), dtype=float32)


In [10]:
# Matrix multiplication
matmul_tensor = tf.linalg.matmul(const_tensor_a, const_tensor_b)
print(matmul_tensor)

# Matrix multiplication with Transpose a
matmul_tensor_a = tf.linalg.matmul(const_tensor_a, const_tensor_b, transpose_a=True)
print(matmul_tensor_a)

# Matrix multiplication with Transpose b
matmul_tensor_b = tf.linalg.matmul(const_tensor_a, const_tensor_b, transpose_b=True)
print(matmul_tensor_b)

tf.Tensor(
[[ 30.  24.  18.]
 [ 84.  69.  54.]
 [138. 114.  90.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[54. 42. 30.]
 [72. 57. 42.]
 [90. 72. 54.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[ 46.  28.  10.]
 [118.  73.  28.]
 [190. 118.  46.]], shape=(3, 3), dtype=float32)


In [11]:
# Exponentiation
pow_tensor_a = tf.pow(const_tensor_a, 2)
print(pow_tensor_a)

pow_tensor_b = tf.pow(const_tensor_b, 2)
print(pow_tensor_b)

tf.Tensor(
[[ 1.  4.  9.]
 [16. 25. 36.]
 [49. 64. 81.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[81. 64. 49.]
 [36. 25. 16.]
 [ 9.  4.  1.]], shape=(3, 3), dtype=float32)


In [12]:
# Exponential function with "e" as the base
exp_tensor_a = tf.exp(const_tensor_a)
print(exp_tensor_a)

exp_tensor_b = tf.exp(const_tensor_b)
print(exp_tensor_b)

tf.Tensor(
[[2.7182817e+00 7.3890562e+00 2.0085537e+01]
 [5.4598152e+01 1.4841316e+02 4.0342880e+02]
 [1.0966332e+03 2.9809580e+03 8.1030840e+03]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[8.1030840e+03 2.9809580e+03 1.0966332e+03]
 [4.0342880e+02 1.4841316e+02 5.4598152e+01]
 [2.0085537e+01 7.3890562e+00 2.7182817e+00]], shape=(3, 3), dtype=float32)


In [13]:
# Square root
sqrt_tensor_a = tf.sqrt(const_tensor_a)
print(sqrt_tensor_a)

sqrt_tensor_b = tf.sqrt(const_tensor_b)
print(sqrt_tensor_b)

tf.Tensor(
[[0.99999994 1.4142134  1.7320508 ]
 [1.9999999  2.236068   2.4494896 ]
 [2.6457512  2.8284268  3.        ]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[2.9999998 2.8284268 2.6457512]
 [2.4494896 2.236068  1.9999999]
 [1.7320508 1.4142134 1.       ]], shape=(3, 3), dtype=float32)


In [14]:
# Division by element
div_tensor = tf.divide(const_tensor_a, const_tensor_b)
print(div_tensor)

# Divide by element and round
floordiv_tensor = tf.math.floordiv(const_tensor_a, const_tensor_b)
print(floordiv_tensor)

tf.Tensor(
[[0.11111111 0.25       0.42857143]
 [0.6666667  1.         1.5       ]
 [2.3333333  4.         9.        ]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[0. 0. 0.]
 [0. 1. 1.]
 [2. 4. 9.]], shape=(3, 3), dtype=float32)


In [15]:
# Division remainder
mod_tensor = tf.math.mod(const_tensor_a, const_tensor_b)
print(mod_tensor)

tf.Tensor(
[[1. 2. 3.]
 [4. 0. 2.]
 [1. 0. 0.]], shape=(3, 3), dtype=float32)
